version: "3"

services:
  app:
    container_name: "hackclub_backend"
    build: .
    env_file:
      - "development.env"
      - "email.env"
    volumes:
    - "./app:/src/app"
    - "./alembic:/src/alembic"
    ports:
    - "8000:80"
    depends_on:
      - db
      - test-db

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'hackclubdb'
    volumes:
    - "./db-data:/var/lib/postgresql/data"

  test-db:
    container_name: "test-db"
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'hackclubtestdb'
