version: "3"

services:
  app:
    container_name: "hackclub_backend"
    build:
      # Change only if your UID or GID != 1000
      #args:
      #  UID: 2000
      #  GID: 2000
      context: .
    env_file:
      - "development.env"
      - "email.env"
      - "cloudinary.env"
    volumes:
    - "./app:/src/app"
    - "./alembic:/src/alembic"
    ports:
    - "8000:80"
    depends_on:
      - db

  db:
    container_name: "hackclub-db"
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'hackclubdb'
    volumes:
    - "./db-data:/var/lib/postgresql"

  test-db:
    container_name: "test-db"
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'hackclubtestdb'

  pg-admin:
    container_name: "pg-admin-hackclub"
    image: dpage/pgadmin4
    ports:
    - "9000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@hackclubrit.com"
      PGADMIN_DEFAULT_PASSWORD: "password"