
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: 'user'
          POSTGRES_PASSWORD: 'password'
          POSTGRES_DB: 'testdb'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
       - uses: actions/checkout@v2
       - name: "Install Packages"
         run: "python3 -m pip install -r requirements.txt"
       # Test
       - name: "Run tests"
         run: "pytest"
         env:
          TEST_DB: "postgresql://user:password@localhost/testdb"
          DATABASE_URL: "postgresql://user:password@localhost/testdb"
          SECRET_KEY: "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
       # Linter
       - name: "Run Linter"
         run: "pylint app"
         
