
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  python-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: 'user'
          POSTGRES_PASSWORD: 'password'
          POSTGRES_DB: 'testdb'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
       - uses: actions/checkout@v2
       - name: "Install Packages"
         run: python3 -m pip install -r requirements.txt
       # Test
       - name: "Run tests"
         run: pytest
         env:
          TEST_DB: "postgresql://user:password@localhost/testdb"
          DATABASE_URL: "postgresql://user:password@localhost/testdb"
       # Linter
       - name: "Run Linter"
         run: pylint app
         
  docker-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Build and run dockerfile"
        # docker-compose requires an email.env file
        run: touch email.env && touch cloudinary.env && docker-compose up -d
      - name: "Test dockerfile"
        run: chmod +x ./scripts/wait_for_it.sh && ./scripts/wait_for_it.sh localhost:8000